# Generated by Django 4.1.3 on 2022-11-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
