# Generated by Django 4.1.3 on 2022-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
